-- Import Violated Rights and Subcategories into catalogo_derechos
-- This script upserts data based on the provided JSON (74 items).
-- Note: schema for catalogo_derechos only contains (id, categoria, subcategoria).

INSERT INTO catalogo_derechos (id, categoria, subcategoria)
VALUES
  (92, 'Derecho a la convivencia familiar y comunitaria (art. N. 14)', 'Interrupcion en los vinculos por alojamiento en instituciones'),
  (93, 'Derecho a la convivencia familiar y comunitaria (art. N. 14)', 'Interrupcion en los vinculos por conflictos familiares'),
  (120, 'Derecho a la libertad (art. 22)', 'Impedimento para expresar las propias ideas, beliefs y culto '),
  (121, 'Derecho a la libertad (art. 22)', 'Privación de libertad personal y ambulatoria'),
  (122, 'Derecho a la libertad (art. 22)', 'Otro derecho a la libertad '),
  (123, 'Derecho al descanso, recreación, deporte y juego (art 23)', 'Privación de descanso'),
  (125, 'Derecho al descanso, recreación, deporte y juego (art 23)', 'Otro Derecho a la recreación, deporte y juego'),
  (126, 'Derecho al ambiente saludable (art. 24)', 'Condiciones ambientales '),
  (81, 'Derecho a la vida (art. N.12)', 'Recién Nacido de Alto Riesgo'),
  (82, 'Derecho a la vida (art. N.12)', 'Otro Derecho a la Vida'),
  (94, 'Derecho a la convivencia familiar y comunitaria (art. N. 14)', 'Interrupción del Derecho de comunicación con los progenitores'),
  (95, 'Derecho a la convivencia familiar y comunitaria (art. N. 14)', 'Otro impedimento para la vida en familia o comunidad'),
  (96, 'Derecho a la identity y a la documentación (art. N.15, 16)', 'Niños sin reconocimiento parental'),
  (97, 'Derecho a la identity y a la documentación (art. N.15, 16)', 'Niños sin información sobre progenitor/flia de origen'),
  (98, 'Derecho a la identity y a la documentación (art. N.15, 16)', 'Identidad de género'),
  (99, 'Derecho a la identity y a la documentación (art. N.15, 16)', 'No Inscripto'),
  (101, 'Derecho a la identity y a la documentación (art. N.15, 16)', 'Nacionalidad'),
  (102, 'Derecho a la identity y a la documentación (art. N.15, 16)', 'Extravio o no actualizado, o rectificación de DNI'),
  (103, 'Derecho a la identity y a la documentación (art. N.15, 16)', 'Otro Derecho a la Documentación'),
  (109, 'Derecho a la salud (art.N.17)', 'Condiciones habitacionales inadecuadas'),
  (110, 'Derecho a la salud (art.N.17)', 'Falta de orientación a Familiares y a la Comunidad'),
  (111, 'Derecho a la salud (art.N.17)', 'Otro Derecho a la Salud'),
  (113, 'Derecho a la educación (art. N.18, 19)', 'Convivencia Escolar (Violencia /Acoso/ bullyng)'),
  (114, 'Derecho a la educación (art. N.18, 19)', 'Exclusión Escolar/Deserción (nunca escolarizado o desvinculado temporalmente)'),
  (118, 'Derecho a la educación (art. N.18, 19)', 'Discriminación por Embarazo, maternidad o paternidad'),
  (119, 'Derecho a la educación (art. N.18, 19)', 'Otro Derecho a la Educación'),
  (112, 'Derecho a la educación (art. N.18, 19)', 'Asistencia irregular o no sostenida'),
  (116, 'Derecho a la educación (art. N.18, 19)', 'Dificultad en el acceso a sistema de apoyo en escolaridad en discapacidad'),
  (117, 'Derecho a la educación (art. N.18, 19)', 'Dificultad en el acceso a programas vinculados a la educacion (paicor, boleto educativo, etc)'),
  (104, 'Derecho a la salud (art.N.17)', 'Dificultad en el acceso y/o sostenimiento a servicios de APS, hospitales o internaciones'),
  (124, 'Derecho al descanso, recreación, deporte y juego (art 23)', 'Falta de acceso a recreación/deporte/juego'),
  (105, 'Derecho a la salud (art.N.17)', 'Dificultad en el acceso y/o sostenimiento de tratamientos médicos especificos'),
  (106, 'Derecho a la salud (art.N.17)', 'Dificultad en el acceso y/o sostenimiento de tratam. de salud mental'),
  (127, 'Derecho al ambiente saludable (art. 24)', 'Otro derecho al ambiente'),
  (107, 'Derecho a la salud (art.N.17)', 'Falta de acceso a tratamientos por consumo problematico'),
  (108, 'Derecho a la salud (art.N.17)', 'Falta o dificultades en el acceso a rehabilitación integral en discapacidad'),
  (1, 'Derecho a la dignidad y a la integridad personal, física, psicológica (art. N.13)', 'Obligación de alimentos de progenitores/otros referentes afectivos'),
  (2, 'Derecho a la dignidad y a la integridad personal, física, psicológica (art. N.13)', 'Explotación económica o sexual /venta y trafico de personas'),
  (115, 'Derecho a la educación (art. N.18, 19)', 'Dificultades en el acceso a la\r\nescolaridad (banco o documentación)\r\n'),
  (84, 'Derecho a la dignidad y a la integridad personal, física, psicológica (art. N.13)', 'Negligencia en el cuidado personal'),
  (85, 'Derecho a la dignidad y a la integridad personal, física, psicológica (art. N.13)', 'violencia  contra la integridad Sexual o Sospecha de la misma'),
  (86, 'Derecho a la dignidad y a la integridad personal, física, psicológica (art. N.13)', 'Exposición a situac. de violencia familiar'),
  (87, 'Derecho a la dignidad y a la integridad personal, física, psicológica (art. N.13)', 'Exposición a situac. de violencia comunitaria'),
  (88, 'Derecho a la dignidad y a la integridad personal, física, psicológica (art. N.13)', 'Exposicion a contextos sexualizados inadecuados'),
  (89, 'Derecho a la dignidad y a la integridad personal, física, psicológica (art. N.13)', 'Violencia institucional'),
  (90, 'Derecho a la dignidad and a la integridad personal, física, psicológica (art. N.13)', 'Inexistencia de adultos protectores'),
  (91, 'Derecho a la dignidad and a la integridad personal, física, psicológica (art. N.13)', 'Otro Derecho a la dignidad e integridad personal'),
  (80, 'Derecho a la salud (art.N.17)', 'Falta o dificultades de acceso a controles de embarazo, parto y\r\nlactancia'),
  (133, 'Derecho a la libre asociación y participación (art. 26)', 'Otro derecho a la libre asociación'),
  (134, 'Derecho a opinar y ser oído (art. 27)', 'A ser Oido en su familia, escuela y comunidad'),
  (135, 'Derecho a opinar y ser oído (art. 27)', 'A expresarse en Servicios Públicos, Admin. y Judiciales'),
  (136, 'Derecho a opinar y ser oído (art. 27)', 'Otro derecho a opinar y ser oído'),
  (137, 'Derecho al trabajo de los adolescentes - Protección contra la explotación laboral (art. 28)', 'Condiciones de trabajo adolescente según legislación vigente'),
  (138, 'Derecho al trabajo de los adolescentes - Protección contra la explotación laboral (art. 28)', 'Otros Derechos al trabajo adolescente / Explotación laboral'),
  (142, 'Derecho a la seguridad social (art. 29)', 'Tarjeta Alimentar'),
  (143, 'Derecho a la seguridad social (art. 29)', 'Otros derechos a la seguridad social'),
  (141, 'Derecho a la seguridad social (art. 29)', 'Dificultad en el acceso a servicios públicos con tarifa social'),
  (139, 'Derecho a la seguridad social (art. 29)', 'DIficultad en el acceso a AUH/Asignación familiar'),
  (3, 'Derecho al ambiente saludable (art. 24)', 'Afectación del niño por  peligro de daño grave o  irreversible al medio ambiente'),
  (4, 'Derecho a la vida (art. N.12)', ' Riesgo de vida'),
  (128, 'Derecho a la dignidad y a la igualdad y no discriminación (art. 10) (incluye art.20 discriminac. Por estado de embarazo, maternidad o paternidad)', 'Divulgación/ Exposición pública o en redes sociales'),
  (132, 'Derecho a la libre asociación y participación (art. 26)', 'Dificultad en el acceso a la participación en espacios públicos'),
  (130, 'Derecho a la libre asociación y participación (art. 26)', 'Dificultad en el acceso a la participación in instituciones públicas/privadas'),
  (131, 'Derecho a la libre asociación y participación (art. 26)', 'Dificultad en el acceso a la participación in organizaciones políticas, culturales , deportivas, religiosas y sociales'),
  (6, 'Derecho a la seguridad social (art. 29)', 'Falta de acceso a obra social de progenitores o referentes afectivos'),
  (140, 'Derecho a la seguridad social (art. 29)', 'Falta de pensiones no contributivas, jubilaciones, subsidios'),
  (83, 'Derecho a la dignidad y a la integridad personal, física, psicológica (art. N.13)', 'Maltrato (violencia física y psicológica sobre los niños)'),
  (129, 'Derecho a la dignidad y a la igualdad y no discriminación (art. 10) (incluye art.20 discriminac. Por estado de embarazo, maternidad o paternidad)', 'derecho a la vida privada'),
  (7, 'Derecho a la dignidad y a la igualdad y no discriminación (art. 10) (incluye art.20 discriminac. Por estado de embarazo, maternidad o paternidad)', 'derecho a la propia imagen'),
  (8, 'Derecho a la dignidad y a la igualdad y no discriminación (art. 10) (incluye art.20 discriminac. Por estado de embarazo, maternidad o paternidad)', 'Derecho a la igualdad y no discriminación'),
  (9, 'Derecho a la dignidad y a la igualdad y no discriminación (art. 10) (incluye art.20 discriminac. Por estado de embarazo, maternidad o paternidad)', 'Discriminacion por embarazo')
ON CONFLICT (id) DO UPDATE SET
  categoria = EXCLUDED.categoria,
  subcategoria = EXCLUDED.subcategoria;
